# Generated by Django 6.0.3 on 2026-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="hint",
            field=models.TextField(blank=True, null=True),
        ),
    ]
