name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Security Scan
      run: bandit -r pyshala/ -ll --exit-zero

  deploy:
    runs-on: ubuntu-latest
    needs: security
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/pyshala
          git pull origin main
          source pyshala/venv/bin/activate
          pip install -r pyshala/requirements.txt
          cd pyshala
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          echo "Deployment successful!"